### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [Petrushevsky-A/Lacerate-ohm#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by Petrushevsky-A** [comment]
Hello. i'm sorry for  late reply. I saw your message, i'm already added the MIT license. I hope that's enough.

Thanks.

**Comment by unixorn** [comment]
Any license is enough to get it on the list. It is up to end users to decide what licenses they're willing to use. No license at all makes it hard for users to determine if they can use it, or if they can modify it for their needs.
